### ISSUE TITLE
Manufacturing of 50 pcs

### ISSUE THREAD

**Issue by KKallas** [KKallas/kiwa#3]

**Comment by KKallas** [comment]
- [ ] ECO
- [ ] Bill of materials
- [ ] Initial Routing documentation
- [ ] Manufacturing order 
- [ ] Material Purchase
- [ ] Manufacturing
- [ ] Testing and debugging // work and documentation to be finished for next production set
